graph TB
    subgraph "Vers3Dynamics Platform"
            subgraph "ZeroClaw - The Body"
                        CLI[CLI and Gateway]
                                    Agent[Agent Orchestrator]
                                                Providers[Model Providers]
                                                            Tools[Tool Execution]
                                                                        Memory[Memory System]
                                                                                end

                                                                                        subgraph "James Library - The Mind"
                                                                                                    RLM[Recursive Lab Meeting]
                                                                                                                RainLab[rain_lab.py]
                                                                                                                            Physics[Acoustic Physics]
                                                                                                                                        Research[Research Corpus]
                                                                                                                                                    Godot[Godot Visualization]
                                                                                                                                                            end
                                                                                                                                                                end

                                                                                                                                                                    User((Researcher))
                                                                                                                                                                        External[External APIs]

                                                                                                                                                                            User --> CLI
                                                                                                                                                                                CLI --> Agent
                                                                                                                                                                                    Agent --> Providers
                                                                                                                                                                                        Agent --> Tools
                                                                                                                                                                                            Agent --> Memory
                                                                                                                                                                                                Tools --> RLM
                                                                                                                                                                                                    RLM --> RainLab
                                                                                                                                                                                                        RainLab --> Physics
                                                                                                                                                                                                            RainLab --> Research
                                                                                                                                                                                                                RainLab --> Godot
                                                                                                                                                                                                                    Providers --> Externalbash scripts/quickstart_lmstudio.shpowershell -ExecutionPolicy Bypass -File .\scriptsComponent	Role	Technology
                                                                                                                                                                                                                    ZeroClaw	Autonomous runtime, tool orchestration, provider management	Rust
                                                                                                                                                                                                                    James Library	Research workflows, recursive reasoning, synthesis	Python
                                                                                                                                                                                                                    Godot Client	Multi-agent visual interface	GDScript
                                                                                                                                                                                                                    This path bootstraps .venv, installs Python dependencies, prepares the embedded ZeroClaw runtime when Cargo is available, and runs a launcher-native health snapshot.

                                                                                                                                                                                                                    Canonical next steps:

                                                                                                                                                                                                                    python rain_lab.py --mode validate
                                                                                                                                                                                                                    python rain_lab.py --mode first-run
                                                                                                                                                                                                                    python rain_lab.py --mode status
                                                                                                                                                                                                                    python rain_lab.py --mode models
                                                                                                                                                                                                                    python rain_lab.py --mode chat --ui auto --topic rain_lab.pyIf Rust or a prebuilt zeroclaw binary is not available yet, the Python research flows still work. Rust-side launcher modes become available after you install Rust or point --zeroclaw-bin at a prebuilt runtime.

                                                                                                                                                                                                                    Full Setup / Development
                                                                                                                                                                                                                    git clone https://github.com/topherchris420/james_library.git
                                                                                                                                                                                                                    cd james_library

                                                                                                                                                                                                                    python bootstrap_local.py
                                                                                                                                                                                                                    cargo build --release --locked
                                                                                                                                                                                                                    python rain_lab.py --mode first-runPython-First Research Flow
                                                                                                                                                                                                                    python rain_lab.py --mode first-run
                                                                                                                                                                                                                    python rain_lab.py --mode chat --topic "your research question"
                                                                                                                                                                                                                    python rain_lab.py --mode rlm --topic "acoustic resonance phenomena"
                                                                                                                                                                                                                    Windows Installer
                                                                                                                                                                                                                    1) Double-click INSTALL_RAIN.cmd
                                                                                                                                                                                                                    2) Wait for install to finish
                                                                                                                                                                                                                    3) Double-click R.A.I.N. Lab from your Desktop or Start Menu
                                                                                                                                                                                                                    4) Optional: run "R.A.I.N. Lab Validate" from the Start Menu for a full readiness check
                                                                                                                                                                                                                    5) Optional: run "R.A.I.N. Lab Health Snapshot" for a quick one-screen status view
                                                                                                                                                                                                                    6) On first launch, guided setup runs automatically and then opens chat
                                                                                                                                                                                                                    Useful Launcher Modes
                                                                                                                                                                                                                    python rain_lab.py --mode health
                                                                                                                                                                                                                    python rain_lab.py --mode validate
                                                                                                                                                                                                                    python rain_lab.py --mode first-run
                                                                                                                                                                                                                    python rain_lab.py --mode status
                                                                                                                                                                                                                    python rain_lab.py --mode models
                                                                                                                                                                                                                    python rain_lab.py --mode providers
                                                                                                                                                                                                                    python rain_lab.py --mode onboard
                                                                                                                                                                                                                    python rain_lab.py --mode gateway
                                                                                                                                                                                                                    Download Binaries
                                                                                                                                                                                                                    If you do not want to build from source, download prebuilt binaries from:

                                                                                                                                                                                                                    https://github.com/topherchris420/james_library/releases
                                                                                                                                                                                                                    Supported release targets and extraction steps are documented in:

                                                                                                                                                                                                                    docs/BINARY_RELEASES.md
                                                                                                                                                                                                                    Project Structure
                                                                                                                                                                                                                    james_library/
                                                                                                                                                                                                                    |-- src/                      # ZeroClaw Rust source
                                                                                                                                                                                                                    |   |-- agent/
                                                                                                                                                                                                                    |   |-- channels/
                                                                                                                                                                                                                    |   |-- gateway/
                                                                                                                                                                                                                    |   |-- memory/
                                                                                                                                                                                                                    |   |-- providers/
                                                                                                                                                                                                                    |   |-- runtime/
                                                                                                                                                                                                                    |   `-- tools/
                                                                                                                                                                                                                    |-- tests/                    # Rust and Python tests
                                                                                                                                                                                                                    |-- benches/                  # Criterion benchmarks
                                                                                                                                                                                                                    |-- scripts/ci/               # CI guard scripts
                                                                                                                                                                                                                    |-- james_library/            # Python research modules
                                                                                                                                                                                                                    |-- rain_lab.py               # Main Python launcher
                                                                                                                                                                                                                    |-- config.example.toml       # Config template
                                                                                                                                                                                                                    |-- Cargo.toml                # Rust workspace manifest
                                                                                                                                                                                                                    `-- pyproject.toml            # Python lint/type/Repo integrity guard: scripts/ci/repo_integrity_guard.py
                                                                                                                                                                                                                    Fails if duplicate src/src tree appears.
                                                                                                                                                                                                                    Fails if embedded dashboard fallback is missing (build.rs or web/dist/index.html).
                                                                                                                                                                                                                    Embedded dashboard fallback: build.rs auto-creates web/dist/index.html if frontend artifacts are absent.
                                                                                                                                                                                                                    Gateway request-path hardening:
                                                                                                                                                                                                                    Reduced allocation pressure in static serving path.
                                                                                                                                                                                                                    Stricter asset path validation.
                                                                                                                                                                                                                    More efficient rate limiting and idempotency cleanup behavior.
                                                                                                                                                                                                                    Development
                                                                                                                                                                                                                    Python
                                                                                                                                                                                                                    pip install -r requirements-dev.txt
                                                                                                                                                                                                                    ruff check .
                                                                                                                                                                                                                    pytest -q
                                                                                                                                                                                                                    Rust
                                                                                                                                                                                                                    cargo fmt --all
                                                                                                                                                                                                                    cargo clippy --all-targets -- -D warnings
                                                                                                                                                                                                                    cargo test
                                                                                                                                                                                                                    cargo check
                                                                                                                                                                                                                    Benchmarks
                                                                                                                                                                                                                    cargo bench --features benchmarks --bench agent_benchmarks
                                                                                                                                                                                                                    Godot Integration
                                                                                                                                                                                                                    python rain_lab.py --mode chat --ui auto --topic "your topic"
                                                                                                                                                                                                                    python rain_lab.py --mode chat --ui on --topic "your topic"
                                                                                                                                                                                                                    --ui auto starts avatars when Godot is available and falls back to CLI when not.

                                                                                                                                                                                                                    Documentation
                                                                                                                                                                                                                    ARCHITECTURE.md
                                                                                                                                                                                                                    PRODUCT_ROADMAP.md
                                                                                                                                                                                                                    CONTRIBUTING.md
                                                                                                                                                                                                                    SECURITY.md
                                                                                                                                                                                                                    docs/PRODUCTION_READINESS.md
                                                                                                                                                                                                                    docs/FIRST_RUN_CHECKLIST.md
                                                                                                                                                                                                                    docs/BINARY_RELEASES.md
                                                                                                                                                                                                                    License
                                                                                                                                                                                                                    MIT License. See LICENSE.

                                                                                                                                                                                                                    Acknowledgement
                                                                                                                                                                                                                    The R.A.I.N. Lab is proudly built on the foundation of ZeroClaw and MIT CSAIL. Huge thanks to both teams for creating such a high-performance, lightweight agent runtime that made this Vers3Dynamics lab possible. by