name: Bolt-Performance-Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  boltperformancescan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run k6 performance tests
        uses: grafana/k6-action@v0.3.0
        with:
          filename: perf-tests/basic.js
          flags: --out json=results/bolt-results.json

      - name: Upload performance artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bolt-performance-results
          path: ./results
